services:
  fmrServer:
    build:
      context: ./apps/server
      target: development
    container_name: fmrServerDev
    ports:
      - '8000:8000'
    restart: unless-stopped
    networks:
      - feelmyrythm-dev

  fmrWeb:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: fmrWebDev
    depends_on:
      fmrServer:
        condition: service_healthy
    ports:
      - '5175:80'
    restart: unless-stopped
    networks:
      - feelmyrythm-dev

networks:
  feelmyrythm-dev:
    name: feelmyrythm-dev
    driver: bridge
